name: arrpilot
version: 11.0.0
confinement: strict
base: core22
# Required but managed manually via Snapcraft dashboard
summary: Self-Hosted Media Server Controller
description: ArrPilot is a self-hosted media server controller for *arr applications
slots:
  dbus-arrpilot:
    interface: dbus
    bus: session
    name: com.gemridge.arrpilot
apps:
  arrpilot:
    command: arrpilot
    extensions:
    - gnome
    plugs:
    - home
    - network
    slots:
    - dbus-arrpilot
parts:
  zenity:
    plugin: nil
    stage-packages:
    - zenity
  arrpilot:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart
